### PR TITLE
10 second scroll on double tap player

### PR DESCRIPTION
**Pull request by IvRRimum**
This comes at the cost of double tap to fullscreen, i guess we could override the the shaka player logic and make and edge case for mobile devices, like here:
https://github.com/google/shaka-player/commit/cf5d893d6ff3dc43da89131570debc30348a1437

### CODE REVIEW

**Comment by IvRRimum** [comment]
But then again, double tap to fullscreen is a lot less used than double tap to 10 sec forward/backward, so i guess it works for now

**Comment by FireMasterK** [comment]
I really want to use https://github.com/google/shaka-player/pull/3373 instead.

**Comment by IvRRimum** [comment]
Like integrate this feature within shaka player api? Or do you want to have this feature integrated into the shaka player repo?

**Comment by FireMasterK** [comment]
I'm interested in the PR in shaka-player, that adds native support for this. I want to avoid additional code here if possible.

**Comment by IvRRimum** [comment]
Ohh, well it depends on them if they want to merge that feature. I will have time next weekend, might be able to do that.

**Comment by Bnyro** [comment]
https://github.com/shaka-project/shaka-player/pull/5943

**Pull request closed without merging**
