### PR TITLE
Frame-by-frame navigation

### PR DESCRIPTION
**Pull request by vr10t**
Navigate one frame at a time using `,` and `.`

### CODE REVIEW

**Review by Bnyro — APPROVED** [review]
LGTM!

**Comment by Bnyro** [comment]
I had to revert the changes due to #2206, I guess that using multiples `,` in line 103 causes a conflict unfortunately.

**Comment by vr10t** [comment]
Hmm, that's odd.. [This](https://github.com/jaywcjlove/hotkeys/blob/862a224672514e392e9ce55a9058429f67122ad5/src/utils.js#L20) is the function that splits the keys in hotkeys-js and from testing, it should parse the string just fine.
Here is the output:
`0:f` `1:m` `2:j` `3:k` `4:l` `5:c` `6:space` `7:up` `8:down` `9:left` `10:right` `11:0` `12:1` `13:2` `14:3` `15:4` `16:5` `17:6` `18:7` `19:8` `20:9` `21:shift+n` `22:shift+,` `23:shift+.` `24:return` `25:.` `26:,`

**Comment by vr10t** [comment]
No problem! We should probably add a comment though, to make sure the keys get split properly if we change them or add more in the future.

**Pull request merged**
