### PR TITLE
Add load more logic to feeds and fix feeds mobile design

### PR DESCRIPTION
**Pull request by IvRRimum**
I have a lot of subcsriptions, I had to wait like 30 seconds to load my feeds before, now happens instantly.

### CODE REVIEW

**Comment by FireMasterK** [comment]
Instead of having a load more, I would rather have it infinitely scroll. Let me know if you would like me to do this, or if you're okay with doing it!

**Comment by IvRRimum** [comment]
I will refactor in like an hour or so

**Comment by IvRRimum** [comment]
Done

**Comment by FireMasterK** [comment]
Thanks! I just made a few improvements for my satisfaction, so that nothing can break with this.

**Pull request merged**
