### PR TITLE
fix: make footer stick to the bottom

### PR DESCRIPTION
**Pull request by rramiachraf**
The current behavior is not visually appealing, and is more noticeable on pages with small amount of content like the register and login pages.

### CODE REVIEW

**Comment by rramiachraf** [comment]
After this commit I've noticed a problem with the search suggestions menu, it started getting on top of the search input making it harder for users to see which letters are being typed.
A quick fix by using `top: 4rem` would solve this but it seems like a hacky way of achieving things.

**Comment by Bnyro** [comment]
I can reproduce the search suggestions issue, couldn't we just give the `main` a `min-height: 80vh` or something? Sure, that wouldn't be as elegant as wrapping it into a flex-container, but it should at least get rid of the issue with the search suggestions.

**Comment by rramiachraf** [comment]
Adding the navbar component inside `main` seems to get rid of the problem.

**Comment by Bnyro** [comment]
Honestly I'm not sure if it looks better like that as we currently don't have any loading indicator so while loading, there's just a big white/black gap in-between the footer and the top bar.
I think this would be an awesome improvement in combination with #2159.

**Review by Bnyro — APPROVED** [review]

**Comment by Bnyro** [comment]
Should be merged after #2192 imo

**Pull request merged**
