### PR TITLE
Design ui2 proposal

### PR DESCRIPTION
**Pull request by IvRRimum**
I hired a designer to redesign piped platform(originally for my own liking). Wondering if Admin would be interested in this:
https://www.figma.com/file/xx5A8vahH9pHVv0NhgKKia/Piped?node-id=1%3A20

There still will be some changes(the burger nav at the top will change more like youtube), mobile design will come tomorrow.

Edit: To see the design click on: 
Screenshot 2021-09-13 at 16 48 13

### CODE REVIEW

**Comment by FireMasterK** [comment]
I do like the designs! Is this just a designer preview? Do you have an actual implantation yoo?

**Comment by IvRRimum** [comment]
Its not implemented yet. It only has been drawn. Maybe you would be interested on coordinating tasks for this redesign. This design is not too complicated, so we could implement it pretty fast.

**Comment by IvRRimum** [comment]
Also check the mobile design

**Comment by IvRRimum** [comment]
Alright, looks like the design part is done. Now will only need to implement it..

**Comment by FireMasterK** [comment]
Nice! That's the most difficult part, more difficult than actually designing it :P

**Comment by filipesmedeiros** [comment]
is this currently being worked on by anyone?

**Comment by FireMasterK** [comment]
Sadly, not that I know of.

**Comment by filipesmedeiros** [comment]
I'd love to help. I'm very new to Vue. With that in mind, do you think I should wait for you (or someone else) and make small contributions on top? Or can I start with the easy parts and you correct any imperfections you find?

Ps. I'm proficient in react and currently learning svelte

**Comment by Mhowser** [comment]
https://ui-v2.piped.pages.dev/ is available for testing now, submit your feedback to #520

**Pull request closed without merging**
