### PR TITLE
Add Watch on YouTube button

### LINKED ISSUE #1611: What Happen To The View On YouTube Button?
### Describe the feature

There used to be a "View On YouTube Button?" which when clicked on will take you to that video on youtube.com. Please bring this button back and please also add a button for [playlists and channels](https://github.com/TeamPiped/Piped/issues/803).

### Why would this be useful to add?

- To quickly go to the video on youtube.com.
- To quickly bookmark the video with the youtube.com URL and not the Piped instance URL.

### Concept(s)

_No response_

### Additional context

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by thecashewtrader**
Closes #1611 and #803

### CODE REVIEW

**Comment by Bnyro** [comment]
That's 3 times the same code:
A button that is rendered if the preference is enabled.

Creating a component here that's just used for the channel page, video page and playlist page would be better!

**Comment by thecashewtrader** [comment]
Thanks for the feedback!

**Comment by Bnyro** [comment]
The conditional statement should be part of the template as well preferably :)

**Comment by thecashewtrader** [comment]
I considered it, but say for example in the future we add an on page toggle for the YouTube button like we have for Hide Recommendations/Comments (unlikely but just as an example), that integrated conditional could cause problems, also it looked a bit more clear this way. It's a semantic issue anyways, I could change it if you want.

**Comment by Bnyro** [comment]
Hmm, I don't think we'll ever need to dynamically hide or show that button, @FireMasterK has the last word :wink:

**Comment by IronMaltese** [comment]
I just wanna put my 2 cents in here

The follow link button should be replaced with the watch on YouTube button since there's no point in hitting follow link for a piped url

**Comment by FireMasterK** [comment]
> there's no point in hitting follow link for a piped URL

Agree with this

**Comment by IronMaltese** [comment]
One last thing: 

The share with time code button should be unchecked by default since I've never shared a video with a time code, and haven't seen anyone do it either

**Comment by thecashewtrader** [comment]
How about this:
- The `v-if` goes into `WatchOnYouTubeButton`
- To just share/follow Piped link -> Copy from URL Bar
- To just share/follow YouTube link -> Use Watch On YouTube Button
- To share/follow Piped/YouTube link *with* timecode -> Use the share dialogue. Therefore, the share with timecode button is checked by default.

@IronMaltese thoughts?

**Review by Bnyro — APPROVED** [review]
LGTM!

**Comment by Bnyro** [comment]
> To just share/follow Piped link -> Copy from URL Bar
> 
Following the Piped link doesn't really make sense currently, true, but think it might make sense as soon as we allow to choose a different Piped instance there so you can share links for the official instance easier while using a smaller or private instance for example.
>  To share/follow Piped/YouTube link _with_ timecode -> Use the share dialogue. Therefore, the share with timecode button is checked by default.
> 
I agree, we should enable sharing with timecode by default now as the dialog would be sorta useless otherwise.

**Comment by thecashewtrader** [comment]
@Bnyro Sorry, I just copied the line so it was `share/follow` instead of just `share` lol

**Pull request merged**
