### PR TITLE
Minimize the video description by default

### PR DESCRIPTION
**Pull request by robertgro**
please for the love of the user experience https://github.com/TeamPiped/Piped/issues/3070

### CODE REVIEW

**Comment by Bnyro** [comment]
In my opinion we should minimize the video description by default instead (even though there's already a preference for it). Moving the buttons up like that looks kinda out of place.

**Comment by robertgro** [comment]
Maybe this is what is what you looking for @Bnyro.

**Comment by Bnyro** [comment]
It would need to be minimzed at `src/components/PreferencesPage.vue` too by default.

Opinion @FireMasterK?

**Comment by robertgro** [comment]
> It would need to be minimzed at `src/components/PreferencesPage.vue` too by default.

This should do the trick.

**Review by Bnyro — APPROVED** [review]

**Review by Bnyro — APPROVED** [review]
Thanks!

**Comment by robertgro** [comment]
You are welcome.

**Pull request merged**
