### PR TITLE
feat: menu and feed start

### PR DESCRIPTION
**Pull request by filipesmedeiros**
i think it's pretty neat, but you're welcome to test it and give some suggestions!

i tested it and it works pretty well on desktop sizes and mobile

### CODE REVIEW

**Comment by FireMasterK** [comment]
The only problem I see is that the build fails due to `sass-loader` not being present! :thinking:

**Comment by filipesmedeiros** [comment]
this is weird, it was a mistake on my part that is unintended! i will fix it asap! 😄

**Comment by filipesmedeiros** [comment]
@FireMasterK you can check it! seems nice now 😄

**Comment by FireMasterK** [comment]
For some odd reason, some menus have a weird black bar and don't occupy the entire screen :thinking: 

image

**Comment by filipesmedeiros** [comment]
yeah! this pr only handles the menu (and the trending page because it was easier

i will pr that asap, but wanted to keep them fairly separated.

i can fix this one thing though, seems easy enough

**Comment by FireMasterK** [comment]
Okay, it happened in the feed and trending page too, which is why I thought it was wierd! (before it loads)

**Comment by filipesmedeiros** [comment]
done!

i'd like to add a loading state eventually

**Pull request merged**
