### PR TITLE
refactor(SubscriptionsPage): styling changes

### PR DESCRIPTION
**Pull request by kskarthik**
- show channel info as cards
- only show sub count info if subs are > 0

image

image

### CODE REVIEW

**Comment by kskarthik** [comment]
i think this PR needs few more changes. Please hold on

**Comment by rozari0** [comment]
> i think this PR needs few more changes. Please hold on

Make it draft PR then.

**Comment by kskarthik** [comment]
Ok, this is ready to merge!

**Comment by FireMasterK** [comment]
Looks good, thanks!

Now that we're hiding the channel subscribed count if its 0, maybe we could also show a message to go subscribe to some channels.

**Pull request merged**
