### PR TITLE
feat(hyperlinking): hyperlinking URLs in the channel descriptions

### PR DESCRIPTION
**Pull request by dotamir**
Fix for #7.
Now with this fix, URLs on channel descriptions are clickable as hyperlinks.

**Note**: Regex for URLs detection is not quite a complete regex. As you know there are complex and more completed regex out there. If you prefer to use a more confident regex, let me know.

Example channel: [here](https://piped.kavin.rocks/channel/UCKlOmM_eB0nzTNiDFZibSSA)

Comments are welcome.

### CODE REVIEW

**Comment by FireMasterK** [comment]
Hey! This would introduce a severe XSS vulnerability!

I will take a look at this tomorrow.

**Comment by dotamir** [comment]
Hey. You're right. So we need to use purify html here?

**Comment by FireMasterK** [comment]
Yes, you're right, there's a mixin for it too. 
v-html calls are unsafe, hence why we use dompurify.

**Comment by dotamir** [comment]
@FireMasterK Just pushed a new commit for the issue you mentioned.

**Comment by FireMasterK** [comment]
Finally got a chance to test it and it works perfectly as expected, thanks!

**Pull request merged**
