### PR TITLE
fix the alignment of tooltip in login & register pages

### PR DESCRIPTION
**Pull request by kskarthik**
image image

### CODE REVIEW

**Comment by Bnyro** [comment]
To be honest, I intentionally placed the tooltips where they are right now.

I'd prefer to keep them as they are, but it's a matter of personal taste.

**Comment by FireMasterK** [comment]
<details>
<summary>
Current design:
</summary>

image
image
</details>

I personally think the information icon could utilize a better position, since currently it looks like it's in a random position. I do like the idea of how it's next to the button, like how this PR showcases. I'm open to other ideas too.

**Comment by kskarthik** [comment]
> Maybe it makes the most sense to add it to the "Login" / "Register" title at the top of the page?
> 
> My idea would be to place it at the top right next to the title element.

I did also try that first. I felt apt beside the buttons. Let me revisit that idea again

**Comment by Bnyro** [comment]
I'd place it more up so that it aligns with the top of the "Login" title, that looks a bit better in my opinion.

**Comment by Bnyro** [comment]
Apart from that I prefer this one to the initial suggestion of this PR :+1:

**Comment by kskarthik** [comment]
@Bnyro you meant this position?

image

**Comment by Bnyro** [comment]
Yes, exactly :+1:

**Review by Bnyro — APPROVED** [review]

**Comment by Bnyro** [comment]
(Approved once the changes are pushed)

**Comment by kskarthik** [comment]
Done!

image 
image

**Review by Bnyro — APPROVED** [review]
Neat, thank you!

**Pull request merged**
