### PR TITLE
Watch on youtube link now includes timestamp

### LINKED ISSUE #1834: Watch on youtube should include timestamp
### Describe the feature

Clicking watch on youtube should bring the user to the timestamp on the piped video being watched

### Why would this be useful to add?

Sometimes I'm halfway through a piped video and the website crashes, so I switch to youtube but I have to move to the timestamp manually

### Concept(s)

_No response_

### Additional context

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by gmnsii**
Closes #1834

### CODE REVIEW

**Comment by FireMasterK** [comment]
Won't this cause issues with channels/playlists?

**Comment by gmnsii** [comment]
The playlists are already not part of the URL are they ? Currently if I am watching a video from a playlist and click to the button to watch it on YouTube, I will be taken to the video without the playlist.

**Comment by gmnsii** [comment]
I added support for playlists anyway, but I don't see what you mean by "channels".

**Comment by FireMasterK** [comment]
I meant to say, the watch on YouTube button on channels / playlists pages, sorry for not being clearer!

**Comment by gmnsii** [comment]
Ah I see, I'll work on that.

**Comment by gmnsii** [comment]
It is fixed now.

**Comment by FireMasterK** [comment]
But, you didn't push any new changes? Am I missing something? :confused:

**Comment by gmnsii** [comment]
It appears second in the list of commits, 65d01f870ad3f9f8f2526e5f2a4250d4e5760bdb

**Comment by thecashewtrader** [comment]
I appreciate the PR, but as per https://github.com/TeamPiped/Piped/pull/1664#issuecomment-1301847273, the watch on youtube button not including the timestamp is an intended thing.

**Comment by gmnsii** [comment]
Not a problem at all. I also added playlist integration (if you are in a playlist and go watch on YouTube you will still be in the playlist) do we keep that ? Though it could be added to the share button instead.

**Comment by thecashewtrader** [comment]
It makes sense to have it include the playlist by default and have an option in the share modal to copy the "vanilla"/video-only link.

**Comment by gmnsii** [comment]
I'll do that then.

**Pull request closed without merging**
