### PR TITLE
Add a seekbar thumbnail preview

### LINKED ISSUE #105: In video thumbnails
Depends on https://github.com/TeamNewPipe/NewPipeExtractor/issues/595

ShakaPlayer supports this already, so that is nice - https://github.com/google/shaka-player/pull/3145

### PR DESCRIPTION
**Pull request by Bnyro**
closes #105

### CODE REVIEW

**Comment by kskarthik** [comment]
how does this feature look like?

**Comment by Bnyro** [comment]
You can test it yourself, run 
`git remote add bnyro https://github.com/bnyro/Piped`,
`git fetch bnyro` and `git checkout bnyro/seekbar-preview`.

**Comment by Bnyro** [comment]
It looks very good though :wink:

**Review by FireMasterK — APPROVED** [review]

**Comment by FireMasterK** [comment]
Thanks! This is really well done!

**Pull request merged**
