### PR TITLE
Fix: Make more text translatable

### PR DESCRIPTION
**Pull request by ChunkyProgrammer**
This PR will make more of the text in the app translatable by adding new strings for text that doesn't already exist in the json file and referencing existing strings in places where the json file wasn't being used

### CODE REVIEW

**Comment by FireMasterK** [comment]
Why did you rename `minimize_description` to `minimize_description_default`?

**Comment by ChunkyProgrammer** [comment]
> Why did you rename `minimize_description` to `minimize_description_default`?

WatchVideo had text that was just "Minimize Description" and I feel like that suits the key better then "Minimize Description By Default". I can change it back if it's easier

**Comment by FireMasterK** [comment]
I see, I just merged #415, please change it in Slovak/sk.json as well, and then I will merge this.

**Comment by ChunkyProgrammer** [comment]
Done

**Comment by FireMasterK** [comment]
Thanks!

**Pull request merged**
