### PR TITLE
Dislike removed

### PR DESCRIPTION
**Pull request by arisuv**
I removed the Dislike font from the video UI, since it is not a feature in YouTube anymore

### CODE REVIEW

**Comment by FireMasterK** [comment]
There are plans to add optional support for ReturnYouTubeDislike with the help of a proxy: https://github.com/TeamPiped/RYD-Proxy

**Comment by arisuv** [comment]
> There are plans to add optional support for ReturnYouTubeDislike with the help of a proxy: https://github.com/TeamPiped/RYD-Proxy

I have been thinking about using https://github.com/Anarios/return-youtube-dislike API it's a good project

**Comment by FireMasterK** [comment]
It's the same API, however that program is used to proxy requests since the ryd backend isn't open source, or freely available.

**Comment by arisuv** [comment]
That's cool! What's the progress?

**Comment by FireMasterK** [comment]
https://github.com/TeamPiped/Piped/issues/643

I'm waiting till July 1st for the poll, and then I will implement something, it's trivial.

**Comment by arisuv** [comment]
Good luck!

**Pull request closed without merging**
